# Exercicio 1 = Objetivo é criar três variáveis: duas para as notas e uma para o resultado da média.
# 1- Definir nota1 e nota2.
# 2- Somar as duas e dividir por 2.
# 3- Armazenar o resultado na variável média.

nota1=7.5
nota2=8.5
media_notas=(nota1+nota2)/2
print(media_notas)

# Exercicio 2
# Módulo '%' Ele não retorna o quociente da divisão, mas sim o que sobra. Por exemplo, 5 % 2 resulta em 1.

num1=3
num2=4
soma=num1+num2
subtracao=num1-num2
multiplicacao=num1*num2
divisao=num1/num2
modulo=num1%num2

print(soma,subtracao,multiplicacao,divisao,modulo)